name: Auto Assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

auto-assign:
    uses: github-brenno-compass/.github/.github/workflows/auto-assign.yml@main
    secrets:
        GITHUB_TOKEN: ${{ github.GITHUB_TOKEN }}
