name: Auto Assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  call-auto-assign:
    uses: github-brenno-compass/.github/.github/workflows/auto-assign.yml@reusable-workflow
    secrets: inherit
