name: Generate Release

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  call-generate-release:
    uses: github-brenno-compass/.github/.github/workflows/generate-release.yml@main
    secrets: inherit
