name: Swiftlint

on:
  pull_request:
    paths:
      - '.swiftlint.yml'
      - 'Sources/**'
      - 'Tests/**'
      
swiftlint:
    uses: github-brenno-compass/.github/.github/workflows/swiftlint.yml@main
